services:
  cda_database:
    image: postgres
    container_name: cda_database
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:5432'
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ['postgres', '-c', 'timezone=${DATABASE_TIMEZONE}']

  cda_adminer:
    image: adminer:latest
    container_name: cda_adminer
    ports:
      - '${ADMINER_PORT}:8080'
    environment:
      - ADMINER_DESIGN=${ADMINER_DESIGN}
    restart: unless-stopped
    depends_on:
      - cda_database

volumes:
  postgres_data: {}
